# Generated by Django 5.2.17 on 2026-09-15 19:44

import django.db.models.deletion
import uuid
import wiki.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wiki', '0002_pendingdeletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.document')),
                ('state', models.BinaryField(default=bytes)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('synced_sequence', models.PositiveBigIntegerField(default=0)),
                ('snapshot', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='format_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='inherit_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.TextField()),
                ('content_type', models.CharField(max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wiki.document')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('policy', models.JSONField(default=wiki.models.default_policy)),
                ('inherit_permissions', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='wiki.folder')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
            bases=(wiki.models.AccessPolicy, models.Model),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='wiki.folder'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='comment', max_length=12)),
                ('body', models.TextField()),
                ('anchor', models.JSONField(default=dict)),
                ('status', models.CharField(default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='wiki.document')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
