# Generated by Django 5.2.17 on 2026-09-16 08:58

import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_collaboration_document_format_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My workspace', max_length=100)),
                ('description', models.CharField(default='Your shared knowledge', max_length=200)),
                ('session_hours', models.PositiveIntegerField(default=24)),
                ('invite_days', models.PositiveIntegerField(default=7)),
                ('invite_uses', models.PositiveIntegerField(default=1)),
                ('login_attempts', models.PositiveIntegerField(default=10)),
                ('login_window_minutes', models.PositiveIntegerField(default=15)),
                ('document_limit_mb', models.PositiveSmallIntegerField(default=5)),
                ('image_limit_mb', models.PositiveSmallIntegerField(default=5)),
                ('image_limit_megapixels', models.PositiveSmallIntegerField(default=16)),
                ('sync_interval_seconds', models.PositiveSmallIntegerField(default=3)),
                ('default_collection', models.CharField(default='Getting started', max_length=100)),
                ('default_document_policy', models.JSONField(default=wiki.models.default_policy)),
            ],
        ),
    ]
