# Generated by Django 5.2.17 on 2026-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_sourcelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_label',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
