# Generated by Django 5.2.17 on 2026-09-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_review_author_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('document', 'Document'), ('table', 'Table'), ('drawio', 'Draw.io'), ('canvas', 'Canvas'), ('file', 'File')], max_length=15),
        ),
    ]
