# Generated by Django 5.2.17 on 2026-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_document_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path_synced',
            field=models.BooleanField(default=False),
        ),
    ]
