# Generated by Django 5.2.17 on 2026-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_folder_group_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='encrypted_ai_config',
            field=models.TextField(blank=True, default=''),
        ),
    ]
