# Generated by Django 5.2.17 on 2026-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_siteconfiguration_encrypted_ai_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='encrypted_google_oauth_client',
            field=models.TextField(blank=True, default=''),
        ),
    ]
