# Generated by Django 5.2.17 on 2026-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_siteconfiguration_encrypted_google_oauth_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_format',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='document',
            name='history_reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='revision_history',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='storage_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='folder',
            name='revision_history',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mountpoint',
            name='revision_history',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='revision_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='inherit_permissions',
            field=models.BooleanField(default=True),
        ),
    ]
