import {boot,host,toolbar,button,dialog,objects,readObjects,writeObjects,graphUndo,error,api} from './shared.js';

export function canvasEditor(){
  graphUndo();let selected=new Set(),zoom=1,pan={x:100,y:100},connecting=false,dragging=false;
  const stage=document.createElement('div');stage.className='canvas-stage';stage.tabIndex=0;stage.setAttribute('aria-label','Canvas. Select cards, use arrow keys to move, Delete to remove.');
  const world=document.createElement('div');world.className='canvas-world';stage.append(world);host.append(stage);
  const svgNS='http://www.w3.org/2000/svg';
  const transform=()=>world.style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;
  function change(fn){if(!boot.write)return;const data=readObjects();const old=structuredClone(data);fn(data);writeObjects(data,old);}
  async function add(type){let fields=type==='text'?[['text','Text','','textarea']]:type==='link'?[['url','URL','https://','url']]:type==='file'?[['file','Wiki document UUID or external file reference']]:[['label','Group name']];const values=await dialog(`Add ${type} card`,fields);if(!values)return;const id=crypto.randomUUID();change(data=>{data.nodes||={};data.nodes[id]={id,type,x:Math.round((60-pan.x)/zoom),y:Math.round((60-pan.y)/zoom),width:type==='group'?500:260,height:type==='group'?350:170,...values};});selected=new Set([id]);render();}
  for(const type of ['text','group','link','file'])button(`Add ${type}`,()=>add(type));
  button('Connect cards',()=>{connecting=!connecting;error(connecting?'Select the source card, then the destination card.':'Connection mode ended.');selected.clear();});
  async function edit(id){const n=readObjects().nodes[id];const key={text:'text',group:'label',link:'url',file:'file'}[n.type];if(!key)throw new Error('This imported card type is preserved but not editable.');const value=await dialog('Edit card',[[key,key,n[key]||'',key==='text'?'textarea':'text'],['color','Color (1–6 or #hex)',n.color||'']]);if(value)change(data=>Object.assign(data.nodes[id],value));}
  button('Edit selected',()=>{if(selected.size!==1)throw new Error('Select one card.');return edit([...selected][0]);});
  button('Delete selected',()=>change(data=>{for(const id of selected)delete data.nodes[id];for(const [id,e] of Object.entries(data.edges||{}))if(selected.has(e.fromNode)||selected.has(e.toNode))delete data.edges[id];selected.clear();}));
  button('Edit connections',async()=>{const data=readObjects(),edges=Object.values(data.edges||{}).filter(e=>!selected.size||selected.has(e.fromNode)||selected.has(e.toNode));if(!edges.length)throw new Error('No connections for this selection.');const e=edges[0];const values=await dialog('Edit connection', [['label','Label',e.label||''],['remove','Type DELETE to remove','']]);if(values)change(d=>{if(values.remove==='DELETE')delete d.edges[e.id];else d.edges[e.id].label=values.label;});});
  button('Zoom out',()=>{zoom=Math.max(.2,zoom/1.2);transform();},{write:false});button('Zoom in',()=>{zoom=Math.min(3,zoom*1.2);transform();},{write:false});
  button('Fit',()=>{const nodes=Object.values(readObjects().nodes||{});if(!nodes.length)return;const x=Math.min(...nodes.map(n=>n.x)),y=Math.min(...nodes.map(n=>n.y));const w=Math.max(...nodes.map(n=>n.x+n.width))-x,h=Math.max(...nodes.map(n=>n.y+n.height))-y;zoom=Math.min(1.5,(stage.clientWidth-60)/w,(stage.clientHeight-60)/h);pan={x:30-x*zoom,y:30-y*zoom};transform();},{write:false});
  function render(){if(dragging)return;world.replaceChildren();const data=readObjects(),nodes=data.nodes||{},edges=data.edges||{};const svg=document.createElementNS(svgNS,'svg');svg.classList.add('canvas-edges');svg.setAttribute('width','1');svg.setAttribute('height','1');world.append(svg);
    for(const e of Object.values(edges)){const a=nodes[e.fromNode],b=nodes[e.toNode];if(!a||!b)continue;const x1=a.x+a.width/2,y1=a.y+a.height,x2=b.x+b.width/2,y2=b.y;const path=document.createElementNS(svgNS,'path');path.setAttribute('d',`M${x1},${y1} C${x1},${y1+70} ${x2},${y2-70} ${x2},${y2}`);svg.append(path);if(e.label){const label=document.createElementNS(svgNS,'text');label.setAttribute('x',(x1+x2)/2);label.setAttribute('y',(y1+y2)/2);label.textContent=e.label;svg.append(label);}}
    for(const n of Object.values(nodes).sort((a,b)=>(a.type==='group'?-1:0)-(b.type==='group'?-1:0))){const card=document.createElement('div');card.className=`canvas-node${selected.has(n.id)?' selected':''}`;card.dataset.type=n.type;card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`${n.type} card: ${n.text||n.label||n.url||n.file||n.id}`);Object.assign(card.style,{left:n.x+'px',top:n.y+'px',width:n.width+'px',height:n.height+'px'});const colors={'1':'#fce0e3','2':'#fae7cf','3':'#f5edbb','4':'#d5eee2','5':'#dce8fc','6':'#eadff5'};if(colors[n.color])card.style.background=colors[n.color];else if(/^#[0-9a-f]{6}$/i.test(n.color||''))card.style.borderColor=n.color;
      const type=document.createElement('div');type.className='card-title';type.textContent=n.type;const content=document.createElement('div');content.className='card-content';content.textContent=n.text||n.label||n.url||n.file||'Card';card.append(type,content);
      if(n.type==='link'&&/^https?:\/\//.test(n.url||'')){const link=document.createElement('a');link.href=n.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Open link ↗';link.onclick=e=>e.stopPropagation();card.append(link);}
      if(n.type==='file'&&/^[0-9a-f-]{36}$/.test(n.file||'')){const link=document.createElement('a');link.href=`/documents/${n.file}/`;link.textContent='Open document ↗';link.onclick=e=>e.stopPropagation();card.append(link);}
      card.ondblclick=()=>{if(boot.write)edit(n.id).catch(e=>error(e.message));};
      card.onpointerdown=e=>{if(e.target.closest('a'))return;e.stopPropagation();if(connecting){if(!selected.size){selected.add(n.id);render();}else{const from=[...selected][0],id=crypto.randomUUID();change(d=>{d.edges||={};d.edges[id]={id,fromNode:from,toNode:n.id,fromSide:'bottom',toSide:'top',toEnd:'arrow'};});connecting=false;selected.clear();render();}return;}
        if(!e.shiftKey&&!selected.has(n.id))selected.clear();selected.add(n.id);card.classList.add('selected');if(!boot.write)return;const resize=e.target.classList.contains('resize-handle'),start={x:e.clientX,y:e.clientY},initial=readObjects();dragging=true;card.setPointerCapture(e.pointerId);
        card.onpointermove=move=>{const dx=(move.clientX-start.x)/zoom,dy=(move.clientY-start.y)/zoom;if(resize){card.style.width=Math.max(100,n.width+dx)+'px';card.style.height=Math.max(70,n.height+dy)+'px';}else{card.style.left=n.x+dx+'px';card.style.top=n.y+dy+'px';}};
        card.onpointerup=up=>{const dx=(up.clientX-start.x)/zoom,dy=(up.clientY-start.y)/zoom;dragging=false;card.onpointermove=null;card.onpointerup=null;change(d=>{for(const id of selected){if(!d.nodes[id]||!initial.nodes[id])continue;if(resize&&id===n.id){d.nodes[id].width=Math.max(100,n.width+dx);d.nodes[id].height=Math.max(70,n.height+dy);}else if(!resize){d.nodes[id].x=initial.nodes[id].x+dx;d.nodes[id].y=initial.nodes[id].y+dy;}}});render();};};
      if(boot.write){const resize=document.createElement('button');resize.type='button';resize.className='resize-handle';resize.setAttribute('aria-label','Resize card');card.append(resize);}world.append(card);
    }transform();}
  stage.onpointerdown=e=>{if(e.target!==stage)return;selected.clear();render();const start={x:e.clientX-pan.x,y:e.clientY-pan.y};stage.setPointerCapture(e.pointerId);stage.onpointermove=move=>{pan={x:move.clientX-start.x,y:move.clientY-start.y};transform();};stage.onpointerup=()=>stage.onpointermove=null;};
  stage.onwheel=e=>{e.preventDefault();zoom=Math.min(3,Math.max(.2,zoom*(e.deltaY<0?1.1:1/1.1)));transform();};
  stage.onkeydown=e=>{if(!boot.write)return;const step=e.shiftKey?20:5;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();change(d=>{for(const id of selected){if(d.nodes[id]){d.nodes[id].x+=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0;d.nodes[id].y+=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;}}});}if(e.key==='Delete')change(d=>{for(const id of selected)delete d.nodes[id];for(const [id,edge] of Object.entries(d.edges||{}))if(selected.has(edge.fromNode)||selected.has(edge.toNode))delete d.edges[id];});};
  objects.observe(render);render();return {setEditable:()=>render()};
}
